package com.inspur.agent.message;

/**
 * The large language model (LLM)'s Chat Message interface.
 * <p>
 *     This interface is used to represent a message in the chat.
 *     All messages in the chat must implement this interface, including different types of llm.
 * </p>
 */
public abstract class Message {
    /**
     * the prompt which is used to generate the result.
     */
    private String prompt;
    /**
     * the result generated by the llm.
     */
    private String result;

    /**
     * Covert the ChatResponse to Message.
     * @param chatResponse the ChatResponse to convert
     * @return the Message that was converted
     */
    public abstract Message fromChatResponse(ChatResponse chatResponse);
}
